/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Snowism (https://sketchfab.com/snowvy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/book-6acc8732df2c4b609e5d4ac52b364a24
Title: Book
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BookModel(props) {
  const { nodes, materials } = useGLTF("3dModel/book/book.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3.geometry}
          material={materials.Sketchy_Siding_Straight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2.geometry}
          material={materials.material_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_1.geometry}
          material={materials.material_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_1.geometry}
          material={materials.material_2_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_2.geometry}
          material={materials.material_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_2.geometry}
          material={materials.material_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_3.geometry}
          material={materials.Cover_01_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_4.geometry}
          material={materials.Cover_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_3.geometry}
          material={materials.material_3_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_4.geometry}
          material={materials.material_5}
        />
      </group>
    </group>
  );
}
useGLTF.preload("/3dModel/book/book.gltf");

export default BookModel;
